const {chromium}=require('playwright'),http=require('http'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../public'),out=path.resolve(__dirname,'../../qa');fs.mkdirSync(out,{recursive:true});
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.svg':'image/svg+xml','.otf':'font/otf','.sql':'text/plain','.md':'text/plain'};
const server=http.createServer((req,res)=>{const uri=decodeURIComponent(req.url.split('?')[0]);const f=path.join(root,uri==='/'?'index.html':uri);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return}try{res.setHeader('Content-Type',MIME[path.extname(f)]||'text/plain');res.end(fs.readFileSync(f))}catch{res.writeHead(404).end()}});
(async()=>{
 await new Promise(r=>server.listen(4173,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.FLORA_QA_CHROMIUM||'/workspace/scratch/abff4305c075/browser-bin/chromium',headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base='http://127.0.0.1:4173/';const check=async(test,fn)=>{await fn();console.log('PASS',test)};
 try{
 await page.goto(base,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);
 await check('initial data, photos and primary action visible',async()=>{assert.equal(await page.locator('.plant-card').count(),6);assert.match(await page.locator('#result-count').innerText(),/12/);assert.equal(await page.locator('#search-form button').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(41, 78, 62)');assert(await page.locator('img').evaluateAll(els=>els.every(i=>i.complete&&i.naturalWidth>0)));});
 await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
 await check('Chinese, Latin and historical synonym search',async()=>{for(const q of ['银杏','GINKGO BILOBA','  Ginkgo    biloba ']){await page.locator('#search').fill(q);assert.equal(await page.locator('.plant-card').count(),1);assert(await page.locator('[data-slug="ginkgo-biloba"]').count())}await page.locator('#search').fill('Rosmarinus officinalis');assert(await page.locator('[data-slug="salvia-rosmarinus"]').count());await page.locator('#search').press('Enter');});
 await check('empty state and reset',async()=>{await page.locator('#search').fill('不存在的植物XYZ');assert.equal(await page.locator('.plant-card').count(),0);assert.equal(await page.locator('.empty-state').count(),1);await page.locator('.empty-state button').click();assert.equal(await page.locator('.plant-card').count(),6)});
 await check('family + use + genus intersection',async()=>{await page.locator('[data-family="Lamiaceae"]').click();assert.equal(await page.locator('.plant-card').count(),4);await page.locator('button[data-use="食用"]').click();assert.equal(await page.locator('.plant-card').count(),3);await page.locator('#genus-filter').selectOption('Mentha');assert.equal(await page.locator('.plant-card').count(),1);assert(await page.locator('[data-slug="mentha-spicata"]').count());await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('.plant-card').count(),1);});
 await check('detail, provenance and direct URL reload',async()=>{await page.locator('.card-heading').click();await page.locator('#detail-dialog').waitFor({state:'visible'});assert.equal(await page.locator('#dialog-title').innerText(),'留兰香');await page.locator('[data-tab="provenance"]').click();assert.match(await page.locator('#detail-panel').innerText(),/CC BY 2.0/);assert.match(await page.locator('#detail-panel').innerText(),/Wikidata/);await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('#dialog-title').innerText(),'留兰香');await page.locator('[data-action="copy-name"]').click();assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/Mentha spicata/);await page.locator('[data-tab="uses"]').click();assert.match(await page.locator('#detail-panel').innerText(),/调味/);await page.screenshot({path:path.join(out,'detail.png')});await page.keyboard.press('Escape');assert.equal(await page.locator('#detail-dialog').isVisible(),false)});
 await check('pagination, sorting and list view',async()=>{await page.locator('.aside-title [data-action="reset"]').click();await page.locator('[aria-label="第 2 页"]').click();assert.equal(await page.locator('.plant-card').count(),6);assert(await page.locator('[data-slug="adiantum-capillus-veneris"]').count());await page.locator('[data-view="list"]').click();assert(await page.locator('#results').evaluate(el=>el.classList.contains('list-view')));await page.locator('#sort').selectOption('latin');assert.equal(await page.locator('.plant-card').first().getAttribute('data-slug'),'adiantum-capillus-veneris')});
 await check('source credits, schema and data download',async()=>{await page.locator('[data-action="credits"]').click();assert.equal(await page.locator('.credit-item').count(),12);await page.locator('[data-action="close"]').click();await page.locator('[data-action="architecture"]').click();assert.equal(await page.locator('.schema-list article').count(),4);await page.locator('[data-action="close"]').click();const download=page.waitForEvent('download');await page.locator('a[download="flora-demo.json"]').click();const d=await download;assert.equal(d.suggestedFilename(),'flora-demo.json');const p=await d.path();assert.equal(JSON.parse(fs.readFileSync(p)).plants.length,12)});
 await check('invalid record and untrusted query are safe',async()=>{await page.goto(base+'?q=%3Cimg%20src%3Dx%20onerror%3Dalert(1)%3E#plant/missing',{waitUntil:'networkidle'});assert.match(await page.locator('#dialog-title').innerText(),/尚未收录/);await page.keyboard.press('Escape');assert.equal(await page.locator('.plant-card').count(),0)});
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto(base,{waitUntil:'networkidle'});await m.evaluate(()=>document.fonts.ready);
 await check('mobile layout, filter and detail interaction',async()=>{assert(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await m.screenshot({path:path.join(out,'mobile.png'),fullPage:true});await m.locator('[data-action="filters"]').click();await m.locator('[data-group="ferns"]').click();assert.equal(await m.locator('.plant-card').count(),1);await m.locator('.card-heading').click();assert.equal(await m.locator('#dialog-title').innerText(),'铁线蕨');await m.locator('[data-tab="provenance"]').click();assert.match(await m.locator('#detail-panel').innerText(),/CC0/);await m.screenshot({path:path.join(out,'mobile-detail.png')});await m.locator('[data-action="close"]').click();});
 await check('narrow phone has no horizontal overflow',async()=>{await m.setViewportSize({width:320,height:740});await m.goto(base,{waitUntil:'networkidle'});assert(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});
 assert.deepEqual(errors,[]);console.log('PASS no browser runtime errors');fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({status:'passed',browser:'Chromium',desktop:'1440x1000',mobile:['390x844','320x740'],browserErrors:errors,date:'2026-09-04'},null,2));
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exit(1)});
