import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
# Individually curated facts and original Chinese summaries; see field-level provenance.
rows=[
('ginkgo-biloba','银杏','Ginkgo biloba','L.','Q43284','gymnosperms','Ginkgoaceae','银杏科','Ginkgo','银杏属','乔木',['观赏','绿化'],['白果','公孙树','銀杏'],'扇叶摇曳，把秋天染成金黄。','落叶乔木，叶片呈扇形，秋季转为金黄色。常见于公园与行道绿化。','中国','扇形叶片，常有两浅裂；叶脉呈多次二叉分枝。','观赏叶形与秋色，也用于城市道路和公园绿化。','种子及外种皮具有毒性风险；本页不提供食用或用药建议。',[]),
('nelumbo-nucifera','荷花','Nelumbo nucifera','Gaertn.','Q16528','angiosperms','Nelumbonaceae','莲科','Nelumbo','莲属','水生草本',['观赏','食用'],['莲','莲花','荷','藕'],'一池清凉，一朵盛夏。','多年生水生植物，圆形叶片挺出水面，花朵大而醒目，地下根状茎膨大成藕。','亚洲','圆形盾状叶，花梗长；花后形成具孔洞的莲蓬。','用于池塘景观；藕与莲子是常见的食材。','',[]),
('salvia-rosmarinus','迷迭香','Salvia rosmarinus','Spenn.','Q102240169','angiosperms','Lamiaceae','唇形科','Salvia','鼠尾草属','灌木',['芳香','食用','观赏'],['Rosemary'],'海风一样清冽的草木香气。','常绿芳香灌木，叶片细长，常见蓝紫色小花。园艺中兼有香草和观赏用途。','地中海地区及邻近区域','细长叶对生，叶背偏白；花小，呈唇形。','叶片用作烹饪香草，也可用于香囊和花园观赏。','',[{'name':'Rosmarinus officinalis','authorship':'L.','sourceUrl':'https://www.wikidata.org/wiki/Q122679'}]),
('camellia-sinensis','茶树','Camellia sinensis','(L.) Kuntze','Q101815','angiosperms','Theaceae','山茶科','Camellia','山茶属','灌木',['食用','观赏'],['茶','茗'],'一芽一叶，连接日常与山野。','常绿灌木或小乔木，嫩叶和芽经不同工艺加工成茶。花色白，叶片有光泽。','中国中南部与东南部','叶片革质，边缘有锯齿；花白色，雄蕊多数。','嫩叶和芽用于制茶；植株也用于庭院和绿篱观赏。','',[]),
('osmanthus-fragrans','桂花','Osmanthus fragrans','Lour.','Q1209922','angiosperms','Oleaceae','木犀科','Osmanthus','木犀属','灌木',['芳香','观赏','食用'],['木犀','桂'],'花朵很小，香气走得很远。','常绿灌木，花簇生于叶腋，花香浓郁。园艺品种的花色和花期各有不同。','东亚','叶对生，叶质较厚；细小花朵成簇开放。','用于庭院观赏、绿篱与芳香景观；花也用于茶饮增香。','',[]),
('monstera-deliciosa','龟背竹','Monstera deliciosa','Liebm.','Q161077','angiosperms','Araceae','天南星科','Monstera','龟背竹属','藤本',['观赏'],['蓬莱蕉','龜背竹'],'把热带森林的一角带进生活。','常绿攀援植物，成熟叶片可形成深裂和孔洞，是常见的室内观叶植物。','墨西哥至巴拿马','成熟叶片宽大，有不规则孔洞与边缘裂片。','主要作为室内盆栽与温暖地区的观叶植物。','植株含刺激性草酸钙晶体，避免儿童和宠物啃咬。',[]),
('mentha-spicata','留兰香','Mentha spicata','L.','Q160114','angiosperms','Lamiaceae','唇形科','Mentha','薄荷属','草本',['芳香','食用'],['绿薄荷','香薄荷','留蘭香','Spearmint'],'指尖一揉，便是清新的夏天。','多年生芳香草本，叶片鲜绿，夏季可见穗状花序。植株能通过根状茎扩展。','欧洲至中国','茎常呈四棱，叶对生；花序细长，呈穗状。','叶片用于茶饮、饮料和菜肴调味，也可作为芳香材料。','',[]),
('lavandula-angustifolia','薰衣草','Lavandula angustifolia','Mill.','Q42081','angiosperms','Lamiaceae','唇形科','Lavandula','薰衣草属','亚灌木',['芳香','观赏'],['狭叶薰衣草','English lavender'],'紫色花穗，收藏阳光的气息。','具芳香的多年生亚灌木，叶狭长，花穗常呈紫色，适合芳香花园与干花材料。','地中海地区','狭长灰绿色叶片，细长花梗顶端聚生小花。','用于花境、干花和芳香材料。','',[]),
('helianthus-annuus','向日葵','Helianthus annuus','L.','Q171497','angiosperms','Asteraceae','菊科','Helianthus','向日葵属','草本',['观赏','食用'],['葵花','朝阳花','Sunflower'],'明亮的花盘，装满夏日阳光。','一年生草本，头状花序大，边缘常为黄色舌状花。种子可供食用或榨油。','北美洲','茎直立，叶宽大；花盘由许多小花组成。','用于观赏、切花；种子可食用，也用于植物油生产。','',[]),
('ocimum-basilicum','罗勒','Ocimum basilicum','L.','Q38859','angiosperms','Lamiaceae','唇形科','Ocimum','罗勒属','草本',['食用','芳香'],['九层塔','罗艻','Basil'],'从香草花园，走向餐桌。','芳香草本，叶片对生，栽培品种丰富。不同品种的叶色、叶形和香味会有差异。','热带亚洲与非洲','茎多为四棱，叶对生；小花排列在枝条上部。','鲜叶或干叶用于料理调味，也可种植于香草花园。','',[]),
('adiantum-capillus-veneris','铁线蕨','Adiantum capillus-veneris','L.','Q4678994','ferns','Pteridaceae','凤尾蕨科','Adiantum','铁线蕨属','蕨类',['观赏'],['铁丝草','鐵線蕨','Maidenhair fern'],'细如铁线，轻如一片羽毛。','多年生蕨类植物，叶柄细而深色，小羽片轻盈。常用于阴湿环境下的观叶栽培。','广布于温暖地区','深色细叶柄，扇形小羽片；孢子囊群位于叶缘附近。','作为盆栽观叶植物，也用于阴湿庭园的景观配置。','',[]),
('metasequoia-glyptostroboides','水杉','Metasequoia glyptostroboides','Hu & W.C.Cheng','Q156800','gymnosperms','Cupressaceae','柏科','Metasequoia','水杉属','乔木',['绿化','观赏'],['Dawn redwood'],'一棵树，留住远古的回响。','落叶针叶乔木，枝叶排列整齐，秋季可转为铜褐色。原产中国，是著名的孑遗植物。','中国','线形叶对生，常排成两列；幼树树冠呈圆锥形。','用于公园、校园和道路等开阔场地的景观绿化。','',[])
]
plants=[]
for n,r in enumerate(rows,1):
 slug,zh,name,author,qid,group,family,familyzh,genus,genuszh,habit,uses,aliases,tagline,description,origin,features,useText,notice,synonyms=r
 url='https://plants.ces.ncsu.edu/plants/'+slug+'/'
 plants.append({'id':'flora:'+slug,'slug':slug,'displayOrder':n,'scientificName':name,'authorship':author,'rank':'species','taxonomicStatus':'demo-reference','acceptedTaxonId':None,'parentTaxonId':'flora:genus:'+genus,'commonNames':[{'name':zh,'language':'zh-Hans','preferred':True,'sourceId':'wikidata','sourceRecordId':qid}]+[{'name':x,'language':'en' if x.isascii() else 'zh','preferred':False,'sourceId':'editorial'} for x in aliases],'synonyms':synonyms,'group':group,'family':{'name':family,'zh':familyzh},'genus':{'name':genus,'zh':genuszh},'habit':habit,'useCategories':uses,'tagline':tagline,'description':description,'origin':origin,'features':features,'uses':[{'category':u,'summary':useText,'sourceId':'editorial','referenceUrl':url,'licenseId':'CC0-1.0','reviewStatus':'demo-curated'} for u in uses],'useSummary':useText,'notice':notice,'mediaId':slug,'sourceRecords':[{'sourceId':'wikidata','recordId':qid,'sourceUrl':'https://www.wikidata.org/wiki/'+qid,'datasetVersion':'retrieved-2026-09-04','retrievedAt':'2026-09-04','licenseId':'CC0-1.0','fields':['scientificName','authorship','preferredCommonName','genus']},{'sourceId':'editorial','recordId':'demo-'+slug,'sourceUrl':url,'datasetVersion':'demo-1.0','retrievedAt':'2026-09-04','licenseId':'CC0-1.0','fields':['family','group','habit','description','origin','features','uses','aliases'],'note':'基于参考网页中的事实独立整理；不复制原站文字，也不将原站内容重新授权为 CC0。'}],'externalIds':{'wikidata':qid,'wfo':None,'wcvp':None,'ipni':None}})
data={'schemaVersion':'1.0.0','dataset':{'id':'flora-demo','version':'demo-1.0','createdAt':'2026-09-04','recordCount':len(plants),'scope':'curated-demo','note':'12 条人工整理示例，尚未导入 WFO / WCVP；名称状态为示例参考，不声称已由其验收。'},'groups':[{'id':'angiosperms','name':'被子植物','latin':'Angiosperms'},{'id':'gymnosperms','name':'裸子植物','latin':'Gymnosperms'},{'id':'ferns','name':'蕨类植物','latin':'Ferns'}],'sources':[{'id':'wikidata','title':'Wikidata','url':'https://www.wikidata.org/','licenseId':'CC0-1.0','licenseUrl':'https://creativecommons.org/publicdomain/zero/1.0/','scope':'结构化名称与标识符'},{'id':'editorial','title':'草木集 · 示例编写','url':'#sources','licenseId':'CC0-1.0','licenseUrl':'https://creativecommons.org/publicdomain/zero/1.0/','scope':'独立撰写的中文摘要和手工整理的事实字段；参考网页权利仍归原作者'}],'plants':plants}
(root/'public/data.json').write_text(json.dumps(data,ensure_ascii=False,indent=2))
print('Built',len(plants),'plants;',len(set(p['family']['name'] for p in plants)),'families')
